### ISSUE TITLE
Сделать общий чат в разных мессенджерах

### ISSUE THREAD

**Issue by petr-kalinin** [petr-kalinin/algoprog#102]
Сейчас есть чат в телеграмме для нижегородских школьников уровня 3+ ("Прога в ННГУ по воскресеньям"), также есть канал алгопрога в телеграмме и есть желание сделать общий чат для алгопрога (#88), тоже в телеграмме.

При всем удобстве телеграмма у него есть и недостатки, в основном -- сложность установки. Хорошо бы сделать параллельные чаты во вКонтакте (и, возможно, в каком-нибудь вайбере) и автоматическую пересылку сообщений между чатами. Кажется, что это очень легко реализовать ботом (есть только во вконтакте и в вайбере есть боты), причем скорее всего уже есть такие готовые боты.

Надо изучить эту тему и реализовать.

**Comment by nmaiss** [comment]
Готовые решения кажется уже есть, для вк например : https://github.com/Whiletruedoend/Vk-to-telegram-transfer-bot. Для вайбера не нашел, но сделать это не сложно, так как у них есть API. Ну а с телегой все ещё проще. 

Могу попробовать это все собрать, к рамках "стажировки", нужен только наверное доступ ко всем этим чатам. Не знаю, есть ли у вас vps-сервер для всего этого, но можно запустить на платформе от гугла (там беслпатно в течении длительного периода).

**Comment by petr-kalinin** [comment]
Думаю уже неактуально, телеграм уже несложно ставится
