### ISSUE TITLE
Наладить тестирование

### ISSUE THREAD

**Issue by petr-kalinin** [petr-kalinin/algoprog#14]
Надо наладить инфраструктуру для тестирования (взяв какой-нибудь широко распространенный фреймворк) и написать тесты на часть кода.

**Comment by syrok0010** [comment]
Предлагаю использовать `jest` для тестирования.
До рефакторинга сервера необходимо все покрыть тестами, чтобы при рефакторинге ничего не сломать.

**Comment by petr-kalinin** [comment]
Я прошу прощения, я не готов этот тикет отдавать в работу незнакомым людям. Вообще, глобальные тикеты я готов доверять только тем, кого я довольно давно знаю, кто давно и успешно занимается на алгопроге.

Плюс конкретно в данном тикете — надо понимать, что тестами надо покрывать далеко не весь код, потому что иначе стоимость поддержания тестов в актуальном состоянии превысит существующую сейчас (без тестов) стоимость фикса багов.

Ну и я пока не планирую проводить никакой глобальный рефакторинг сервера; если вы хотите этим заняться у себя, пожалуйста, но вливать ваш код я почти наверняка не буду.

**Comment by syrok0010** [comment]
Понял насчет рефакторинга.
Будете ли вы вливать тесты?

**Comment by petr-kalinin** [comment]
Закрываю, базовая инфраструктура тестов есть и работает.
