### ISSUE TITLE
Обновить менеджер пакетов

### ISSUE THREAD

**Issue by syrok0010** [petr-kalinin/algoprog#227]
Обновить `package-lock.json` до 2 версии или использовать `yarn` как лучшую альтернативу `npm`

**Comment by petr-kalinin** [comment]
А зачем? Что это даст? Меня полностью устраивает то, как сейчас у меня работает пакетный менеджер.

P.S. Не надо, пожалуйста, заводить такие глобальные тикеты. Вообще, список тикетов — это в первую очередь план для потенциальных стажировок на алгопроге (https://algoprog.ru/material/internship). Если у вас есть мысли по глобальным изменениям, лучше обсудите это со мной в личке.

**Comment by syrok0010** [comment]
Что даст?
1. Более умную работу с зависимостями. Например: для jest требуется `node-notifier` версии >= 8 в package.json Алгопрога используется версия 7 этой зависимости. При попытке установки jest npm просто выдает ошибку, в то время как yarn автоматически использует 7ую версию для алгопрога и 8ую для jest.
2. Yarn устанавливает зависимости параллельно, улучшая производительность.

Миграция с Npm на Yarn не является сложной. Необходимо лишь глобально установить yarn на локальной машине `npm i -g yarn` , удалить в репозитории файл `package-lock.json` и добавить автоматически сгенерированный `yarn.lock`

**Comment by petr-kalinin** [comment]
Давайте попробуем, если вы сделаете ПР, я его потестирую и, возможно, волью.

Diamond dependency на данный момент, кажется не есть большая проблема, но параллельная установка может быть полезной для более быстрых релизов.

**Comment by petr-kalinin** [comment]
Залилось в https://github.com/petr-kalinin/algoprog/commit/78cc4f2059c2b5042b46950662a6a1607a15cb44 и https://github.com/petr-kalinin/algoprog/commit/6f151c89bae83bc89f9f402135fc8b57eac520ec
